export const books = [
    { name: 'JavaScript Assertivo', id: 1, src: require('../../assets/books/1.jpeg') },
    { name: 'Clean Code', id: 2, src: require('../../assets/books/2.jpeg') },
    { name: 'Código Limpo', id: 3, src: require('../../assets/books/3.jpeg') },
    { name: 'Arquitetura Limpa', id: 4, src: require('../../assets/books/4.jpeg') },
    { name: 'Refatoração', id: 5, src: require('../../assets/books/5.jpeg') },
    { name: 'Padrões de Projeto', id: 6, src: require('../../assets/books/6.jpeg') },
    { name: 'O Programador Pragmático', id: 7, src: require('../../assets/books/7.jpeg') },
    { name: 'Código Completo', id: 8, src: require('../../assets/books/8.jpeg') },
    { name: 'Entendendo Algoritmos', id: 9, src: require('../../assets/books/9.jpeg') },
    { name: 'Estruturas de Dados', id: 10, src: require('../../assets/books/10.jpeg') },
    { name: 'Java Efetivo', id: 11, src: require('../../assets/books/11.jpeg') },
    { name: 'Java Essencial', id: 12, src: require('../../assets/books/12.jpeg') },
    { name: 'Desenvolvimento Web Moderno', id: 13, src: require('../../assets/books/13.jpeg') },
    { name: 'Banco de Dados Moderno', id: 14, src: require('../../assets/books/14.jpeg') },
    { name: 'Aprendendo SQL', id: 15, src: require('../../assets/books/15.jpeg') },
    { name: 'Engenharia de Software', id: 16, src: require('../../assets/books/16.jpeg') },
    { name: 'Sistemas Operacionais', id: 17, src: require('../../assets/books/17.jpeg') },
    { name: 'Redes de Computadores', id: 18, src: require('../../assets/books/18.jpeg') },
    { name: 'Segurança da Informação', id: 19, src: require('../../assets/books/19.jpeg') },
    { name: 'Fundamentos de Python', id: 20, src: require('../../assets/books/20.jpeg') }
];